name: Publish to NPM

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: |
          npm ci
          
      - name: Run linting
        run: |
          npm run lint
          
      - name: Run type checking
        run: |
          npm run type-check
          
      - name: Build package
        run: |
          npm run build
          
      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
          
      - name: Publish to NPM
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release v${{ steps.get_version.outputs.VERSION }}
          body: |
            ## Changes in v${{ steps.get_version.outputs.VERSION }}
            
            - Auto-generated release from tag push
            - Package published to NPM: https://www.npmjs.com/package/@tedweixx/mcp-coding-best-practices
            
            ## Installation
            ```bash
            npm install -g @tedweixx/mcp-coding-best-practices
            ```
            
            ## Usage
            ```bash
            npx -y @tedweixx/mcp-coding-best-practices
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}