name: Publish to NPM

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: |
          npm ci
          
      - name: Run linting
        run: |
          npm run lint
          
      - name: Run type checking
        run: |
          npm run type-check
          
      - name: Build package
        run: |
          npm run build
          
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
      - name: Update package version
        run: |
          npm version ${{ steps.get_version.outputs.VERSION }} --no-git-tag-version
          
      - name: Publish to NPM
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            ## Changes in v${{ steps.get_version.outputs.VERSION }}
            
            - Auto-generated release from tag push
            - Package published to NPM: https://www.npmjs.com/package/@tedweixx/mcp-coding-best-practices
            
            ## Installation
            ```bash
            npm install -g @tedweixx/mcp-coding-best-practices
            ```
            
            ## Usage
            ```bash
            npx -y 
            ```
          draft: false
          prerelease: false